### PR TITLE
Logic refactor

### LINKED ISSUE #47: Remove fatal/panic error in internal library
## Description
Multiple internal functions within libs triggers fatal errors with `gologger.Fatal()`. These errors are all likely recoverable and should be propagated upstream:

Eg. https://github.com/projectdiscovery/asnmap/blob/5c984871652df1523edfb657254a087deb8cd6eb/libs/client.go#L206

### LINKED ISSUE #48: Client.GetData removes valid results if previously retrieved
## Description
Multiple calls to `Client.GetData` for close network IPs/CIDRs causes valid results to be removed from the response due to some internal embedded deduplication logic. As a client instance, it would be expected that the function returns stable results or an error.

### PR DESCRIPTION
**Pull request by Mzack9999**
## Description
This PR contains the following changes (some breaking-change in functions signature syntax):
- removed internal gologger fatal and errors propagated upstream => Closes #47 
- Added DefaultClient => Unblocks https://github.com/projectdiscovery/mapcidr/issues/138
- Fixed unwanted data removal on reused client => Closes #48 and closes https://github.com/projectdiscovery/interactsh/pull/427 (indirectly)
- Single threaded as anyway multi-thread was ineffective due to unwanted data removal

### CODE REVIEW

**Review by tarunKoyalwar — APPROVED** [review]
lgtm !  Approved with a message

- [x] Update README.md (since we added new flag `-file` in this PR)

**Review by ehsandeep — CHANGES_REQUESTED** [review]
```console
./asnmap -d google.com -silent

142.250.0.0/15
2404:6800::/34
2404:6800:4000::/37
2404:6800:4800::/45
2404:6800:4808::/46
2404:6800:480c::/47
2404:6800:480e::/48
```

IPv6 ranges in CLI output are optional and get included when `-v6` is used.

**Review by ehsandeep — COMMENTED** [review]
- [ ] Update check using as lib - https://github.com/projectdiscovery/asnmap#use-asnmap-as-a-library

**Comment by Mzack9999** [comment]
Note: this PR might require a major release version due to breaking changes in the syntax

**Review by ehsandeep — APPROVED** [review]

**Pull request merged**
