### PR TITLE
fix JSON file output

### LINKED ISSUE #176: `-output` option is not working
Take for example:

`asnmap -a AS20940 -j`

vs

`asnmap -a AS20940 -j -o test.json`

The latter of the two does not work, it's not a  big deal as can just redirect stdout to a file but ideally `-o` should write the results to a file.

### PR DESCRIPTION
**Pull request by dogancanbakir**
Closes #176.

```console
$ go run asnmap.go -a AS20940 -j -o output.json

   ___   _____  __              
  / _ | / __/ |/ /_ _  ___ ____ 
 / __ |_\ \/    /  ' \/ _  / _ \
/_/ |_/___/_/|_/_/_/_/\_,_/ .__/
                         /_/ 

                projectdiscovery.io

[INF] Current asnmap version v1.0.5 (latest)

$ cat output.json | jq | head -20
[
  {
    "timestamp": "2023-09-25 11:45:02.301681257 +0000 UTC",
    "input": "AS20940",
    "as_number": "AS20940",
    "as_name": "AKAMAI-ASN1",
    "as_country": "NL",
    "as_range": [
      "2.16.0.0/23",
      "2.16.2.0/24"
    ]
  },
  {
    "timestamp": "2023-09-25 11:45:02.301777549 +0000 UTC",
    "input": "AS20940",
    "as_number": "AS20940",
    "as_name": "AKAMAI-ASN1",
    "as_country": "NL",
    "as_range": [
      "2.16.4.0/22",
```

### CODE REVIEW

**Review by Mzack9999 — CHANGES_REQUESTED** [review]
Actually we do a lot of work:
```
Response => Result => Slice of results with manual marshaling => json line
```
Probably we can refactor the code so that each response mapped to a result results in a json line directly:
```
Response => intializeResult => Result => json line
```

**Review by Mzack9999 — APPROVED** [review]
implementation: lgtm
tests fail because API gives 502

**Review by ehsandeep — CHANGES_REQUESTED** [review]
- [ ] asnmap `-j` option write output in **json** format, we can update it write in **json line** format to keep it uniform like other pd tools.
- [ ] when `-j` option is used with `-o`, output gets written to only file but not displayed to stdout like other pd tools, we can fix that as well.

**Review by ehsandeep — CHANGES_REQUESTED** [review]
CLI output gets written to file but not visible to stdout.

```
./asnmap -a AS20940 -o test
```

**Pull request merged**
